package empilhadeiraautoguiadaia.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import javax.swing.JPanel;
import empilhadeiraautoguiadaia.controller.InteligenciaController;
import empilhadeiraautoguiadaia.model.Populacao;
import empilhadeiraautoguiadaia.model.Coordenadas;
import java.util.ArrayList;

/**
 *
 * @author skyli
 */
public class Principal extends javax.swing.JFrame {
    /**
     * @param args the command line arguments
     */
    private String mapa[][] = {{"NO","NS" ,"NS" ,"NS" ,"NL" ,"NO","NS" ,"NS" ,"NL" ,"NO","X"},
                               {"OL","ONS","NS" ,"NS" ,"SL" ,"OL","ON" ,"NL" ,"OS" ,"SL",""},
                               {"O ","NS" ,"NS" ,"NS" ,"NS" ,"L ","OSL","O"  ,"NS" ,"NL",""},
                               {"OS","NS" ,"NS" ,"NL" ,"ONS","S" ,"NS" ,"SL" ,"ONL","OL",""},
                               {"ON","NSL","ON" ,"L"  ,"ON" ,"NS","NS" ,"NS" ,"SL" ,"SO","X"},
                               {"OS","NS" ,"L"  ,"O"  ,"S"  ,"NS","NS" ,"NS" ,"NS" ,"NL",""},
                               {"ON","NS" ,"SL" ,"OL" ,"ONS","N" ,"NL" ,"NO" ,"NS" ,"NL",""},
                               {"O" ,"N"  ,"NS" ,"S"  ,"N"  ,"L" ,"OL" ,"OS" ,"NS" ,"NL",""},
                               {"OL","OL" ,"ONS","NSL","OL" ,"OL","OS" ,"NS" ,"NS" ,"L" ,""},
                               {"SL","OS" ,"NS" ,"NS" ,"SL" ,"OS","NS" ,"NS" ,"NS" ,"SL",""}};
    
    private int taxaMutacao;
    private int taxaPopulacao;
    private int taxaCrossover;
    private int numeroGenes;
    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
        initTela();
        initLabirinto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPopulacao = new javax.swing.JLabel();
        lblCrossOver = new javax.swing.JLabel();
        lblMutacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empilhadeira AutoGuiada ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Entrada");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Saída");

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("População:");

        jLabel4.setText("Taxa de Crossover:");

        jLabel5.setText("Taxa de mutação:");

        lblPopulacao.setMaximumSize(new java.awt.Dimension(53, 14));
        lblPopulacao.setMinimumSize(new java.awt.Dimension(53, 14));
        lblPopulacao.setName("jlblPopulacao"); // NOI18N

        lblCrossOver.setName("jlblCrossover"); // NOI18N

        lblMutacao.setName("jlblMutacao"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 635, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCrossOver)
                            .addComponent(lblMutacao))))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCrossOver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMutacao))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTela(){
        taxaMutacao = 3;
        taxaCrossover = 60;
        taxaPopulacao = 1000;
        numeroGenes   = 100;
        
        lblCrossOver.setText(String.valueOf(taxaCrossover) + " %");
        lblMutacao.setText(String.valueOf(taxaMutacao) + " %");
        lblPopulacao.setText(String.valueOf(taxaPopulacao));
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InteligenciaController controller = new InteligenciaController();
        
        controller.setTaxaDeCrossover(taxaCrossover);
        controller.setTaxaDeMutacao(taxaMutacao);
        controller.setSolucao(montaSolucao());
        controller.setNumGenes(numeroGenes);
        controller.setLabirinto(mapa);
        
        Populacao populacao = new Populacao(numeroGenes, taxaPopulacao);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void initLabirinto(){
        initNodos();
        
    }
            
    public void initNodos(){
        JPanel labirinto[][] = new JPanel[12][12];
        int coordenadaX = 0, coordenadaY = 0;
        coordenadaY = 60;
        coordenadaX = 50;
        
        for (int y = 0; y < 10; y++) {
            JPanel nodo = new JPanel();
            nodo.setSize(50, 40);
            nodo.setOpaque(false);
//            nodo.setBackground(Color.white);
            nodo.setLocation(coordenadaX, coordenadaY);
            nodo.setVisible(true);
            nodo.setLayout(null);
            
            this.add(nodo);
            
            for (int x = 0; x < 10; x++) {
                labirinto[x][y] = nodo;
                
                coordenadaX += 50;
                
                nodo = new JPanel();
                nodo.setSize(50, 40);
                nodo.setOpaque(false);
//                nodo.setBackground(Color.white);
                nodo.setLocation(coordenadaX, coordenadaY);
                nodo.setLayout(null);
                if (!mapa[y][x].equals(" ")){
                    nodo = initParedes(mapa[y][x],nodo,x,y);
                }
                
                this.add(nodo);
            }
            coordenadaY += 40;
            coordenadaX = 50;
        }
    }
    
    public JPanel initParedes(String value,JPanel nodo,int x,int y){
        JPanel parede; 
        int counter = 0;
        String newValue;
        Color corParede = Color.blue;
        boolean lgAdiciona = false;
        
        while(true){
            try{
                newValue = value.substring(counter, counter + 1);
                counter++;
            }
            catch(Exception e){
                break;
            }
            
            parede = new JPanel();
            parede.setVisible(true);
            
            switch(newValue){
                case "N":
                    parede.setBackground(corParede);
                    parede.setSize(50,4);
                    parede.setLocation(0, 0);
                    break;
                case "O":
                    parede.setBackground(corParede);
                    parede.setSize(4,40);
                    parede.setLocation(0, 0);
                    break;
                case "L":
                    parede.setBackground(corParede);
                    parede.setSize(4,40);
                    parede.setLocation(46, 0);
                    break;
                case "S":
                    parede.setBackground(corParede);
                    parede.setSize(50,4);
                    parede.setLocation(0, 36);
                    break;
            }
            
            nodo.add(parede);
        }
        
        return nodo;
    }
    //Metodo responsavel por monstar a solucao    
    private ArrayList<Coordenadas> montaSolucao(){
        ArrayList<Coordenadas> solucao = new ArrayList<Coordenadas>();
        solucao.add(new Coordenadas(11,0));
        solucao.add(new Coordenadas(11,4));
        
        return solucao;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCrossOver;
    private javax.swing.JLabel lblMutacao;
    private javax.swing.JLabel lblPopulacao;
    // End of variables declaration//GEN-END:variables
}
