/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.view;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author skyli
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initLabirinto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empilhadeira AutoGuiada ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Entrada");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Saída");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(661, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private String mapa[][] = {{"NO","NS" ,"NS" ,"NS" ,"NL" ,"NO","NS" ,"NS" ,"NL" ,"NO"},
                               {"OL","ONS","NS" ,"NS" ,"SL" ,"OL","ON" ,"NL" ,"OS" ,"SL"},
                               {"O ","NS" ,"NS" ,"NS" ,"NS" ,"L ","OSL","O"  ,"NS" ,"NL"},
                               {"OS","NS" ,"NS" ,"NL" ,"ONS","S" ,"NS" ,"SL" ,"ONL","OL"},
                               {"ON","NSL","ON" ,"L"  ,"ON" ,"NS","NS" ,"NS" ,"SL" ,"SO"},
                               {"OS","NS" ,"L"  ,"O"  ,"S"  ,"NS","NS" ,"NS" ,"NS" ,"NL"},
                               {"ON","NS" ,"SL" ,"OL" ,"ONS","N" ,"NL" ,"NO" ,"NS" ,"NL"},
                               {"O" ,"N"  ,"NS" ,"S"  ,"N"  ,"L" ,"OL" ,"OS" ,"NS" ,"NL"},
                               {"OL","OL" ,"ONS","NSL","OL" ,"OL","OS" ,"NS" ,"NS" ,"L" },
                               {"SL","OS" ,"NS" ,"NS" ,"SL" ,"OS","NS" ,"NS" ,"NS" ,"SL"}};
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void initLabirinto(){
        initNodos();
        
    }
            
    public void initNodos(){
        JPanel labirinto[][] = new JPanel[12][12];
        int coordenadaX = 0, coordenadaY = 0;
        coordenadaY = 60;
        coordenadaX = 50;
        
        for (int y = 0; y < 10; y++) {
            JPanel nodo = new JPanel();
            nodo.setSize(50, 40);
            nodo.setOpaque(false);
//            nodo.setBackground(Color.white);
            nodo.setLocation(coordenadaX, coordenadaY);
            nodo.setVisible(true);
            nodo.setLayout(null);
            
            this.add(nodo);
            
            for (int x = 0; x < 10; x++) {
                labirinto[x][y] = nodo;
                
                coordenadaX += 50;
                
                nodo = new JPanel();
                nodo.setSize(50, 40);
                nodo.setOpaque(false);
//                nodo.setBackground(Color.white);
                nodo.setLocation(coordenadaX, coordenadaY);
                nodo.setLayout(null);
                if (!mapa[y][x].equals(" ")){
                    nodo = initParedes(mapa[y][x],nodo);
                }
                
                this.add(nodo);
            }
            coordenadaY += 40;
            coordenadaX = 50;
        }
    }
    
    public JPanel initParedes(String value,JPanel nodo){
        JPanel parede; 
        int counter = 0;
        String newValue;
        Color corParede = Color.blue;
        
        while(true){
            try{
                newValue = value.substring(counter, counter + 1);
                counter++;
            }
            catch(Exception e){
                break;
            }
            
            parede = new JPanel();
            parede.setVisible(true);
            
            switch(newValue){
                case "N":
                    parede.setBackground(corParede);
                    parede.setSize(50,4);
                    parede.setLocation(0, 0);
                    break;
                case "O":
                    parede.setBackground(corParede);
                    parede.setSize(4,40);
                    parede.setLocation(0, 0);
                    break;
                case "L":
                    parede.setBackground(corParede);
                    parede.setSize(4,40);
                    parede.setLocation(46, 0);
                    break;
                case "S":
                    parede.setBackground(corParede);
                    parede.setSize(50,4);
                    parede.setLocation(0, 36);
                    break;
            }
            nodo.add(parede);
        }
        
        return nodo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
